import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/<catsincorpurrate>/styles/Home.module.css";
import CatList from "../components/CatList";
import { useState, useEffect, useMemo, useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState(null);
  // error would maybe show a 505 page?
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(true);
  const [sort, setSort] = useState(null);
  const [activeButtonIndex, setActiveButtonIndex] = useState(null);
  const [buttonClicked, setButtonClicked] = useState(null);
  const scrollRef = useRef(null);

  const filteredCatData = useMemo(() => {
    if (!data) {
      return null;
    }

    if (sort === "descending") {
      // [...data.cats] - creating a clone of the original array, because you dont want to manipulate the existing one
      return [...data.cats].sort((a, b) => b.cutenessLevel - a.cutenessLevel);
    }
    if (sort === "ascending") {
      return [...data.cats].sort((a, b) => a.cutenessLevel - b.cutenessLevel);
    }

    return data.cats;
  }, [data, sort]);

  useEffect(() => {
    setTimeout(() => {
      fetch("/api/cats")
        .then((response) => response.json())
        .then((data) => {
          console.log(data);
          setData(data);
          setLoading(false);
        })
        .catch((error) => {
          setError(true);
          setLoading(false);
        });
    }, 1000);
  }, []);

  const handleClick = (index) => {
    setActiveButtonIndex(index);
  };

  useEffect(() => {
    if (scrollRef.current && buttonClicked !== null) {
      scrollRef.current.scrollTo({
        top: 0,
        behavior: "smooth",
      });
      setButtonClicked(null);
    }
  }, [buttonClicked]);

  return (
    <>
      <Head>
        <title>Cats Incorpurrate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={`${styles.main} ${inter.className}`}>
        {/* header component */}
        <header className={styles.navbar}>
          <nav className={styles.navbar}>
            <a>Cats Incorpurrate</a>
            <div className={styles.buttonBox}>
              <button
                className={`${styles.btn} ${
                  activeButtonIndex === 0 ? styles.active : ""
                }`}
                onClick={() => {
                  setButtonClicked(0);
                  handleClick(0);
                  setSort(null);
                }}
              >
                Unsort
              </button>
              <button
                className={`${styles.btn} ${
                  activeButtonIndex === 1 ? styles.active : ""
                }`}
                onClick={() => {
                  setButtonClicked(1);
                  handleClick(1);
                  setSort("descending");
                }}
              >
                Much Cute
              </button>
              <button
                className={`${styles.btn} ${
                  activeButtonIndex === 2 ? styles.active : ""
                }`}
                onClick={() => {
                  setButtonClicked(2);
                  handleClick(2);
                  setSort("ascending");
                }}
              >
                Not Cute
              </button>
            </div>
          </nav>
        </header>
        {/* header component */}
        {/* Content component */}
        <main className={styles.center} ref={scrollRef}>
          <p className={styles.paragraph}>
            Greetings, cat lover! <br></br>Please navigate between the buttons in the navbar to sort the cats
            based on cuteness.
          </p>
          <div>
            {loading && <div>Loading...</div>}
            {error && <div>Something went wrong</div>}
            {data && <CatList data={filteredCatData} />}
          </div>
          <footer className="footer">
            <div className="container">
              <div className="row">
                <div className="col-md-6">
                  <p>&copy; 2023 Josies Website. All rights reserved.</p>
                </div>
              </div>
            </div>
          </footer>
        </main>
        {/* main component */}
      </div>
    </>
  );
}
